name: hw2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  animated_bottom_navigation_bar: ^1.3.0
  http: ^1.1.0
  country_state_city: ^0.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/weather_status/